// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Carlos Pérez",
            "email": "xnzperez.dev@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/bets": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Obtiene las apuestas paginadas. Permite filtrar por estado o deporte.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Apuestas"
                ],
                "summary": "Listar apuestas del usuario",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Número de página (default 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items por página (default 10)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filtrar por estado (pending, WON, LOST)",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filtrar por deporte (cs2, nba)",
                        "name": "sport_key",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/betting.GetBetsResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Permite al usuario registrar una apuesta, descontando saldo automáticamente.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Apuestas"
                ],
                "summary": "Crear una nueva apuesta",
                "parameters": [
                    {
                        "description": "Datos de la apuesta",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/betting.PlaceBetRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Apuesta creada exitosamente",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Error de validación o saldo insuficiente",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/bets/{id}/resolve": {
            "patch": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Actualiza el estado de la apuesta. Si es WON, paga al usuario y genera la transacción.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Apuestas"
                ],
                "summary": "Resolver una apuesta (Ganada/Perdida)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID de la apuesta (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Resultado (WON/LOST)",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/betting.ResolveBetRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Apuesta resuelta correctamente",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Error de validación",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Error interno",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/stats": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Calcula métricas clave como ganancia neta, porcentaje de aciertos y total apostado.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Analytics"
                ],
                "summary": "Obtener estadísticas (ROI, WinRate)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/betting.StatsResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/transactions": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Muestra los movimientos de dinero (depósitos, apuestas, pagos) paginados.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Analytics"
                ],
                "summary": "Historial de Transacciones",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Número de página",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items por página",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/betting.GetTransactionsResponse"
                        }
                    },
                    "500": {
                        "description": "Error interno",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "betting.Bet": {
            "type": "object",
            "properties": {
                "ai_prediction": {
                    "description": "--- CORRECCIÓN ---\nUsamos ` + "`" + `column:ai_prediction` + "`" + ` para evitar que GORM genere \"a_iprediction\".\nUsamos *string (puntero) para que si no hay predicción, se guarde como NULL en la BD.",
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "details": {
                    "description": "Details se guarda como JSONB en Postgres para poder hacer consultas avanzadas dentro del JSON en el futuro.\nEn Go lo manejamos como string (o []byte) conteniendo el JSON crudo.",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_parlay": {
                    "type": "boolean"
                },
                "odds": {
                    "type": "number"
                },
                "resulted_at": {
                    "description": "Puntero porque inicialmente es NULL",
                    "type": "string"
                },
                "sport_key": {
                    "description": "Ej: \"cs2\", \"nba\"",
                    "type": "string"
                },
                "stake_units": {
                    "type": "number"
                },
                "status": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                },
                "user_notes": {
                    "type": "string"
                }
            }
        },
        "betting.GetBetsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/betting.Bet"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "betting.GetTransactionsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/betting.Transaction"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "betting.PlaceBetRequest": {
            "type": "object"
        },
        "betting.ResolveBetRequest": {
            "type": "object",
            "properties": {
                "outcome": {
                    "description": "\"WON\" o \"LOST\"",
                    "type": "string"
                }
            }
        },
        "betting.StatsResponse": {
            "type": "object",
            "properties": {
                "net_profit": {
                    "description": "Ganancia/Pérdida neta",
                    "type": "number"
                },
                "roi": {
                    "description": "Retorno de Inversión (%)",
                    "type": "number"
                },
                "total_bets": {
                    "type": "integer"
                },
                "total_lost": {
                    "type": "integer"
                },
                "total_pending": {
                    "type": "integer"
                },
                "total_returned": {
                    "description": "Total recibido (ganancias + stake devuelto)",
                    "type": "number"
                },
                "total_wagered": {
                    "description": "Total apostado",
                    "type": "number"
                },
                "total_won": {
                    "type": "integer"
                },
                "win_rate": {
                    "description": "% de aciertos",
                    "type": "number"
                }
            }
        },
        "betting.Transaction": {
            "type": "object",
            "properties": {
                "amount": {
                    "description": "Positivo (Depósito/Ganancia) o Negativo (Apuesta/Retiro)",
                    "type": "number"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "description": "Ej: \"Apuesta en Vitality vs G2\"",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "reference_id": {
                    "description": "ID de la apuesta relacionada (si aplica)",
                    "type": "string"
                },
                "type": {
                    "description": "\"BET_PLACED\", \"BET_PAYOUT\", \"DEPOSIT\"",
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "description": "\"Inserte el token JWT con el prefijo Bearer. Ejemplo: 'Bearer eyJhbGci...'\"",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Sports Analytics API",
	Description:      "API profesional para seguimiento de apuestas y estadísticas deportivas.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
